import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Travel Itinerary — AI Travel Planner | Nyala',
  description: 'View your personalized AI travel itinerary with day-by-day activities, hotels, restaurants, and attractions. Generated by our free AI travel planner.',
  keywords: 'travel itinerary, ai travel itinerary, travel planning, ai travel planner, itinerary template',
  openGraph: {
    title: 'Travel Itinerary — AI Travel Planner | Nyala',
    description: 'View your personalized AI travel itinerary with day-by-day activities, hotels, and attractions.',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Travel Itinerary — AI Travel Planner | Nyala',
    description: 'View your personalized AI travel itinerary generated by our free AI travel planner.',
  },
};

export default function ItineraryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}

